"""WeChat for Windows (微信)."""

SLUG = "wechat"
TITLE = "WeChat for Windows (微信)"

TIPS = """\
- [seed · launch] Prefer `launch_app(name="wechat")` (it tries the global hotkey + tray + start menu) over double-clicking the desktop icon — duplicate launches are usually rejected by the running instance.
- [seed · hotkey-is-toggle] **`Ctrl+Alt+W` is a TOGGLE, not a "raise to front".** Pressing it when WeChat is **hidden** shows the main window; pressing it when WeChat is **already visible** HIDES it. So after a successful `launch_app(name="wechat")` (which already brings the window forward via `weixin://` URI / tray / hotkey internally), do **NOT** press `Ctrl+Alt+W` again "to make sure it's focused" — that just hides it, and then the next `focus_window(title_substring="微信")` returns `no visible window`, which feels like the launch failed but actually you just toggled it back off. Repeating launch_app + ctrl+alt+w in a loop creates a show/hide oscillation that wastes 4-6 steps. Rule: after `launch_app(wechat)` reports `ok=True`, the next action should be the actual work (search a contact, type, click) — NOT another keypress to "re-focus". **Before pressing `Ctrl+Alt+W` AT ALL** (even as a fallback / "let me just make sure"), first probe with `focus_window(title_substring="微信")` — if it returns success, WeChat is already visible on the desktop and pressing the hotkey would hide it; skip the keypress and go straight to the real work. Only press `Ctrl+Alt+W` when `focus_window` reports `no visible window` (i.e. the window is genuinely hidden / minimized to tray). Never `launch_app` + `ctrl+alt+w` in the same step.
- [seed · tray] WeChat lives in the system tray (the green chat-bubble icon among the small icons on the **right of the bottom taskbar**). To open the main window: right-click the tray icon -> "Show main panel", or just left-click the tray icon.
- [seed · detached-chat-window] Double-clicking a contact can open an independent chat window. Before typing, use `focus_window(title_substring="联系人名")` (or `focus_window(title_substring="微信")`) to ensure keystrokes land in the intended chat window; `ctrl+alt+w` usually returns to the main WeChat window only.
- [seed · click-contact] After clicking a contact / group in the left chat list, focus **automatically jumps into the input box at the bottom-right** of the window — you do NOT need to click the input box separately. Just `type` your text and press Enter to send. (Useful chain: search contact → Enter → type message → Enter.)
- [seed · click-contact-no-l3] **Don't be tricked by the auto-attached L3 after a contact click.** When you click a contact in the left list, the cursor stays on the contact row but the new chat view opens far to the right. The L3 cursor-local tile (and the post-click pixel-change %) only sees the row's hover-state change — typically <1% — which looks like a "miss" but is **not**. Trust the click landed: just `type` your message next. If you really want visual confirmation, call `screenshot(level="active_window")` for a fresh L2; do **not** keep re-clicking the same contact.
- [seed · reorder-after-send] After you send a message, that chat often jumps to the top of the left list and shifts other rows. If you need to message multiple contacts in sequence, take a fresh `screenshot(level="active_window")` before selecting the next contact to avoid stale-row misclicks.
- [seed · input] In the chat input box: **Enter** sends the message immediately, **Shift+Enter** inserts a newline. So if you have a multi-line message, paste the whole block first (newlines stay as soft breaks), then press Enter once to send the whole thing.
- [seed · input-box-truncates-visually] **The chat input box has a fixed small height and only shows the LAST few lines of the staged text — earlier lines are scrolled out of view, NOT lost.** When you `type` (clipboard-paste) a long / multi-line message, the screenshot will typically show only the tail (e.g. the last `\n——宝宝的AI小助手` line) and the rest looks "missing". **Do NOT** assume the typing failed and do NOT press Ctrl+A / retype — that just doubles the message or wipes the correct text. Trust the `typed N chars` tool result; the full content is staged. Either (a) just press Enter to send, or (b) if you really must verify, scroll inside the input box (PageUp / mouse wheel over the input area) before retyping. The `typed N chars` count from the tool is the source of truth, the visual tail is not.
- [seed · search] Use Ctrl+F inside WeChat to open the global search box; type a contact / group name to jump straight to that chat.
- [seed · at-mention] **In a group chat, to @ someone you must `type` first, then commit with Enter — NOT click an icon. And do it in TWO stages, because the popup is slow to filter.** Workflow: focus the group's input box → **stage 1**: `type(text="@")` ALONE (just the literal `@` character) → wait briefly (the member-picker popup floats **above** the input area; the first row is auto-highlighted, and at this point it lists members in WeChat's default order — typically recently-active first). Then `screenshot(level="active_window")` to see the popup. → **stage 2 — branch on what you see**: (a) if the auto-highlighted **first row IS your target**, just press `Return` immediately — done, the `@` becomes a `@昵称 ` chip. (b) if the first row is NOT the target, NOW `type(text="对方昵称")` (clipboard-paste handles CJK fine) — the popup live-filters down to matches, the first match becomes auto-highlighted → press `Return` to confirm. Either way the typed text is replaced with a styled `@昵称 ` mention chip and the popup closes; then continue typing the rest of your message and press `Return` to send. **Why two stages**: WeChat's @ popup re-renders / re-filters with a few-hundred-ms lag; if you `type("@对方昵称")` as one blob, the popup may still be on its initial unfiltered list when your name characters land, the first row is wrong, and pressing Return @s the wrong person. Typing `@` alone first lets you VERIFY the first row before committing, which is often free (the target is already #1). **Do NOT** click the popup rows — keyboard is faster and avoids row-shift misclicks. If the popup didn't appear at all (typed in wrong window, etc.), Backspace to clear and retry. To @ multiple people in the same message, repeat the whole stage-1 + maybe-stage-2 + Return cycle for each one.
- [seed · voice-to-text] **WeChat itself can transcribe voice messages — use it instead of trying to play / record audio.** When a chat contains a voice message ("语音", a small bubble with a duration like `3"` / `5"`): right-click directly on the **voice bubble itself** (the gray rounded rectangle showing the waveform + duration — NOT the avatar, NOT the timestamp, NOT empty space around it) → a context menu opens whose **first item is "语音转文字" (convert voice to text)**. **Then commit with the keyboard, NOT another mouse click** — the menu-item click is the trap that causes 10+ wasted steps (model reads the menu screenshot, writes "Let me click it", but emits no tool_call → loops forever). **Correct keyboard chain — issue ALL of these tool_calls in the SAME turn, no screenshot in between:** `right_click(coordinate=[bubble_x, bubble_y])` → `key("Down")` (highlights the first menu item, "语音转文字") → `key("Return")` (commits). After ~1-3 s the transcription appears as **plain text BELOW the voice bubble in the same chat row** (still part of that message, no new message created, nothing sent to the other party). Only NOW take `screenshot(level="active_window")` and read the text visually. This is the **only** sane way to "understand" a voice message — do NOT try to capture audio, do NOT click the play button (it just plays sound which the agent can't hear). Works for both incoming and your own voice messages. The transcription stays attached to the bubble persistently, so if the same chat already has 译文 below a 语音 bubble, just screenshot it directly without re-doing the right-click dance.
- [seed · voice-to-text-target] **Right-click the voice BUBBLE, not the surrounding chat row.** A WeChat voice message row contains: the sender's avatar (left or right edge), a small white-on-gray timestamp above, and the **voice bubble itself** — a rounded rectangle ~100-300 px wide showing a triangular play icon + waveform marks + the duration like `3"` / `5"`. The right-click MUST land **inside that rounded rectangle** for the "语音转文字" option to appear in the context menu. If you right-click on the avatar, the timestamp, or empty space next to the bubble, you get either no menu or a different menu (e.g. avatar → contact card menu). Read the bubble's center pixel off a fresh `screenshot(level="active_window")` of the chat — don't eyeball "around y=478" from memory; voice bubbles for different durations have visibly different widths and the row Y shifts as new messages arrive. If you're not sure which element is the voice bubble, hover and take an L3 cursor_local tile first — voice bubbles are unmistakable (waveform + duration suffix `"`).
- [seed · send-file] **Preferred path for "send a file" tasks — open WeChat FIRST, no separate File Explorer needed.** Workflow: `launch_app(name="wechat")` → focus the right contact → above the chat input box there is a small toolbar with a **file (folder/paperclip) icon** → click it → a Windows "Open" dialog appears (it IS a mini File Explorer; you can browse folders, sort by date, see thumbnails — everything you'd open Explorer for). In the dialog you can either (a) **type the file's absolute path directly into the filename box** (e.g. `C:\\Users\\you\\Downloads\\foo.png`) and press Enter — fastest if you already know the path, or (b) navigate to the folder via the address bar (Ctrl+L → type path → Enter), then click the desired file (sort by "Date modified" descending to find the **latest** file). The file is then staged in the input area; press Enter once more to actually send it. Works for images, PDFs, videos, anything WeChat accepts. **Do NOT** open a separate File Explorer window first — it adds steps and gains nothing.
- [seed · send-file-clipboard] If the image is **already in your clipboard** (e.g. you just used Win+Shift+S to grab a screenshot, or some other App copied it): focus the WeChat chat input box → **Ctrl+V** pastes the image directly as a staged attachment → Enter to send. (For files already on disk, prefer the paperclip-dialog path above — Ctrl+C on a file in Explorer also works for clipboard-paste, but only do that if Explorer is **already open** for some other reason.)
- [seed · send-file-via-shell-copy] **Fastest path when you already know the absolute path of a local image / file (and WeChat is open at the right contact):** copy the file *itself* to the clipboard from PowerShell, then Ctrl+V into the WeChat input box — staged as an attachment, Enter to send. The clipboard accepts a CF_HDROP file list, so this works for **any** file type WeChat accepts (.png/.jpg/.pdf/.docx/.mp4/...). One-liner:
  `run_shell(cmd="powershell -NoProfile -Command \"Set-Clipboard -Path 'C:\\full\\path\\to\\file.ext'\"")`
  Then `focus_window(title_substring="微信")` (or the contact's chat window) → click the input box (or trust focus is already there after a contact click) → `key("ctrl+v")` → `key("Return")`. Beats the paperclip-dialog path when you don't need to browse — zero icon clicks, zero dialog navigation. Works for clipboard-pasting **multiple** files too: `Set-Clipboard -Path 'a.png','b.pdf'` then one Ctrl+V stages them all.
"""

LAUNCHER = {
    "name": "WeChat",
    "description": "WeChat for Windows (微信). Tray-resident green chat-bubble.",
    "shortcut": "ctrl+alt+w",
    "uri": "weixin://",
    "exe": "wechat",
    # WeChat 4.0+ ("新版微信") renamed the main process from `WeChat.exe` to
    # `Weixin.exe`; the window title stays "微信" on both. We must accept
    # either name, otherwise `_find_windows()` filters out the already-visible
    # window (process mismatch) → Step 1 returns empty → Step 2 hotkey toggles
    # the visible window HIDDEN → backend reports "could not launch" even
    # though WeChat was right there on the desktop.
    "process": r"(weixin|wechat)\.exe",
    "window_title": "微信",
    # WeChat cold-start (process spawn → main window visible) regularly takes
    # 4-6s on Windows; the default 1.5-2.5s per-method poll is too short and
    # causes launch_app to report ok=False even though the URI / exe path
    # actually launched it. Bumping to 7s keeps each method's wait long enough
    # that the foreground window is detected before we move on / report failure.
    "launch_timeout_s": 7.0,
}
